"""empty message

Revision ID: 19b4340712c4
Revises: 44ead5ffb0c4
Create Date: 2014-09-28 13:45:08.347287

"""

# revision identifiers, used by Alembic.
revision = '19b4340712c4'
down_revision = '44ead5ffb0c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
