"""empty message

Revision ID: 33aa6476612d
Revises: f7e6fb805d0
Create Date: 2014-09-28 15:39:59.768255

"""

# revision identifiers, used by Alembic.
revision = '33aa6476612d'
down_revision = 'f7e6fb805d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
