"""empty message

Revision ID: 44ead5ffb0c4
Revises: 5770e352d47a
Create Date: 2014-09-27 22:07:40.896960

"""

# revision identifiers, used by Alembic.
revision = '44ead5ffb0c4'
down_revision = '5770e352d47a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('prev1_grade', sa.Float(), nullable=True))
    op.add_column('scholarship', sa.Column('prev2_grade', sa.Float(), nullable=True))
    op.drop_column('scholarship', 'prev_grade')
    op.drop_column('scholarship', 'prev_two_grade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('prev_two_grade', mysql.FLOAT(), nullable=True))
    op.add_column('scholarship', sa.Column('prev_grade', mysql.FLOAT(), nullable=True))
    op.drop_column('scholarship', 'prev2_grade')
    op.drop_column('scholarship', 'prev1_grade')
    ### end Alembic commands ###
