"""empty message

Revision ID: 5770e352d47a
Revises: None
Create Date: 2014-09-27 14:21:26.180408

"""

# revision identifiers, used by Alembic.
revision = '5770e352d47a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prev_grade', sa.Float(), nullable=True),
    sa.Column('prev_two_grade', sa.Float(), nullable=True),
    sa.Column('all_grade', sa.Float(), nullable=True),
    sa.Column('grade_conditions', sa.Text(), nullable=True),
    sa.Column('area_state', sa.String(length=255), nullable=True),
    sa.Column('area_city', sa.String(length=255), nullable=True),
    sa.Column('income', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recruitment_time', sa.Text(), nullable=True),
    sa.Column('etc', sa.Text(), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_prev1_grade', sa.Float(), nullable=True),
    sa.Column('user_prev2_grade', sa.Float(), nullable=True),
    sa.Column('user_all_grade', sa.Float(), nullable=True),
    sa.Column('user_grade_condition', sa.Text(), nullable=True),
    sa.Column('user_area_state', sa.String(length=255), nullable=True),
    sa.Column('user_area_city', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('scholarship')
    ### end Alembic commands ###
