"""empty message

Revision ID: 5cd0f0e73d1
Revises: 9ac0ba8077e
Create Date: 2014-09-28 14:13:59.716566

"""

# revision identifiers, used by Alembic.
revision = '5cd0f0e73d1'
down_revision = '9ac0ba8077e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_student_num', sa.String(length=255), nullable=False))
    op.drop_column('user', 'user_studentnum')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_studentnum', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'user_student_num')
    ### end Alembic commands ###
