"""empty message

Revision ID: 9ac0ba8077e
Revises: 19b4340712c4
Create Date: 2014-09-28 13:54:12.786230

"""

# revision identifiers, used by Alembic.
revision = '9ac0ba8077e'
down_revision = '19b4340712c4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_studentnum', sa.String(length=255), nullable=False))
    op.drop_column('user', 'user_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'user_studentnum')
    ### end Alembic commands ###
