"""empty message

Revision ID: f7e6fb805d0
Revises: 5cd0f0e73d1
Create Date: 2014-09-28 14:55:43.614374

"""

# revision identifiers, used by Alembic.
revision = 'f7e6fb805d0'
down_revision = '5cd0f0e73d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
